
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to create (e.g., dev, prod)'
        required: true
        default: 'prod'
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      my_value: ${{ steps.step1.outputs.result }}
    steps:
      - name: Generate Output
        id: step1
        run: echo "result=Hello World" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1  # Waits for job1 to complete
    steps:
      - name: Use Output from Job1
        run: echo "Received value: ${{ needs.job1.outputs.my_value }}"